services:
  nginx:
    build:
      context: ./nginx
      args:
        S3_HOSTNAME: s3.openschema.ai
        MINIO_HOSTNAME: minio.openschema.ai
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live/s3.openschema.ai/fullchain.pem:/etc/nginx/certs/s3.openschema.ai/fullchain.pem:ro
      - /etc/letsencrypt/live/s3.openschema.ai/privkey.pem:/etc/nginx/certs/s3.openschema.ai/privkey.pem:ro
      - /etc/letsencrypt/live/minio.openschema.ai/fullchain.pem:/etc/nginx/certs/minio.openschema.ai/fullchain.pem:ro
      - /etc/letsencrypt/live/minio.openschema.ai/privkey.pem:/etc/nginx/certs/minio.openschema.ai/privkey.pem:ro
    depends_on:
      s3:
        condition: service_healthy
  s3:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - /data:/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 5s
      timeout: 3s
      retries: 30
